=== NovaTecConsulting/stereotype-check/stereotype.check.plugin/src/main/resources/checkstyle-stereotype-override.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:sc="http://www.novatec-gmbh.de/checkstyle-stereotype-override"
	targetNamespace="http://www.novatec-gmbh.de/checkstyle-stereotype-override">
	<xsd:element name="stereotypes" type="sc:StereotypesType" />
	<xsd:complexType name="StereotypesType">
		<xsd:sequence>
			<xsd:element name="dependency" type="sc:DependencyType"
				minOccurs="0" maxOccurs="unbounded" />
			<xsd:element name="stereotype" type="sc:StereotypeType"
				minOccurs="0" maxOccurs="unbounded" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="DependencyType">
		<xsd:attribute name="from" type="xsd:string" use="required" />
		<xsd:attribute name="to" type="xsd:string" use="required" />
		<xsd:attribute name="allowed" type="xsd:boolean"
			default="true" />
	</xsd:complexType>

	<xsd:complexType name="StereotypeType">
		<xsd:sequence>
			<xsd:element name="postfix" minOccurs="0" maxOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="name" type="xsd:string" use="required" />
					<xsd:attribute name="condition" type="sc:ConditionType"
						use="required" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="annotation" minOccurs="0" maxOccurs="unbounded">
				<xsd:complexType>
					<xsd:sequence>
						<xsd:element name="annotationname" minOccurs="0"
							maxOccurs="unbounded">
							<xsd:complexType>
								<xsd:attribute name="name" type="xsd:string" use="required" />
							</xsd:complexType>
						</xsd:element>
					</xsd:sequence>
					<xsd:attribute name="name" type="xsd:string" use="optional" />
					<xsd:attribute name="condition" type="sc:ConditionType"
						use="required" />
					<xsd:attribute name="overridemode" type="sc:OverrideMode"
						default="replace" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="baseclass" minOccurs="0" maxOccurs="unbounded">
				<xsd:complexType>
					<xsd:sequence>
						<xsd:element name="baseclassname" minOccurs="0"
							maxOccurs="unbounded">
							<xsd:complexType>
								<xsd:attribute name="name" type="xsd:string" use="required" />
							</xsd:complexType>
						</xsd:element>
					</xsd:sequence>
					<xsd:attribute name="name" type="xsd:string" use="optional" />
					<xsd:attribute name="condition" type="sc:ConditionType"
						use="required" />
					<xsd:attribute name="overridemode" type="sc:OverrideMode"
						default="replace" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="interface" minOccurs="0" maxOccurs="unbounded">
				<xsd:complexType>
					<xsd:sequence>
						<xsd:element name="interfacename" minOccurs="0"
							maxOccurs="unbounded">
							<xsd:complexType>
								<xsd:attribute name="name" type="xsd:string" use="required" />
							</xsd:complexType>
						</xsd:element>
					</xsd:sequence>
					<xsd:attribute name="name" type="xsd:string" use="optional" />
					<xsd:attribute name="condition" type="sc:ConditionType"
						use="required" />
					<xsd:attribute name="overridemode" type="sc:OverrideMode"
						default="replace" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="package" minOccurs="0" maxOccurs="unbounded">
				<xsd:complexType>
					<xsd:attribute name="name" type="xsd:string" use="required" />
					<xsd:attribute name="condition" type="sc:ConditionType"
						use="required" />
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
		<xsd:attribute name="id" type="xsd:ID" use="required" />
	</xsd:complexType>

	<xsd:simpleType name="ConditionType">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="sufficient" />
			<xsd:enumeration value="necessary" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="OverrideMode">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="replace" />
			<xsd:enumeration value="extend" />
		</xsd:restriction>
	</xsd:simpleType>
</xsd:schema>

=== NovaTecConsulting/stereotype-check/stereotype.check.plugin.test/src/test/resources/stereotype-allowoverride-extend-override.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
    Copyright 2016 NovaTec Consulting GmbH
   
    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at
   
        http://www.apache.org/licenses/LICENSE-2.0
   
    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
 -->

<sc:stereotypes
	xmlns:sc="http://www.novatec-gmbh.de/checkstyle-stereotype-override"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.novatec-gmbh.de/checkstyle-stereotype-override checkstyle-stereotype-override.xsd ">

	<stereotype id="businessservice">
		<interface
			name="info.novatec.architecture.check.testclasses.core.fwk.api.bl.bs.ApiBusinessService"
			condition="sufficient" overridemode="extend" />
	</stereotype>

	<stereotype id="businessservice2">
		<interface condition="sufficient" overridemode="extend">
			<interfacename
				name="info.novatec.architecture.check.testclasses.core.fwk.api.bl.bs.ApiBusinessService2" />
		</interface>
	</stereotype>

	<stereotype id="entity">
		<baseclass condition="sufficient" overridemode="extend">
			<baseclassname
				name="info.novatec.architecture.check.testclasses.app1.main.data.entity.common.BaseEntity" />
			<baseclassname
				name="info.novatec.architecture.check.testclasses.app1.main.data.entity.CustomerConcern" />
		</baseclass>
	</stereotype>

	<stereotype id="entity2">
		<baseclass
			name="info.novatec.architecture.check.testclasses.app1.main.data.entity.common.BaseEntity2"
			condition="sufficient" overridemode="extend" />
	</stereotype>

</sc:stereotypes>
